Costs = {
    cg = 5,
    infantry = {oil = 0, iron = 0, osr = 2},
    artillery = {oil = 0, iron = 2, osr = 1},
    armor = {oil = 1, iron = 2, osr = 1},
    fighter = {oil = 2, iron = 1, osr = 1},
    bomber = {oil = 2, iron = 2, osr = 1},
    submarine = {oil = 1, iron = 2, osr = 1},
    cruiser = {oil = 2, iron = 3, osr = 2},
    carrier = {oil = 4, iron = 3, osr = 3},
    battleship = {oil = 3, iron = 4, osr = 3}
}
