Alliance = {
    china = 'allies',
    uk = 'allies',
    usa = 'allies',
    ussr = 'allies',
    germany = 'axis',
    italy = 'axis',
    japan = 'axis'
}

Prefixes = {
    b = 'uk', uk = 'b',
    c = 'china', china = 'c',
    g = 'germany', germany = 'g',
    j = 'japan', japan = 'j',
    n = 'neutral', neutral = 'n',
    t = 'italy', italy = 't',
    r = 'ussr', ussr = 'r',
    u = 'usa', usa = 'u'
}
