function isCommand(name)
    local force = commandForce(name)
    return force == 'army' or force == 'air' or force == 'fleet'
end

function commandNation(command)
    local name = command.getName()
    if name == 'cfighter' then return command.getVar('nation')
    else return name:lower():match('%b[](%a+)%b[]') end
end

function commandForce(name) return name:lower():match('^%b[]%a+%b[]%s%w+%s(%a+)') end
